import { useRef, useState } from "react";
import { BadgeCheck, FileCheck2, ShieldCheck, UploadCloud } from "lucide-react";
import api, { apiError, assetUrl } from "../../api/client";
import { PageHeader, StatusBadge } from "../../components/UI";
import { useAuth } from "../../context/AuthContext";
import { useToast } from "../../context/ToastContext";

export default function CertificationPage() {
  const { user, refreshUser } = useAuth(); const { showToast } = useToast(); const [file, setFile] = useState(null); const [uploading, setUploading] = useState(false); const inputRef = useRef(null); const profile = user.supplierProfile || {};
  const upload = async () => { if (!file) return; setUploading(true); try { const body = new FormData(); body.append("certificate", file); await api.post("/suppliers/certification", body); await refreshUser(); setFile(null); showToast("Certification submitted for admin review."); } catch (err) { showToast(apiError(err), "error"); } finally { setUploading(false); } };
  return <div><PageHeader eyebrow="Supplier trust" title="Farm certification" description="Submit certification documents to strengthen buyer confidence and qualify organic listings." /><div className="certification-layout"><section className="panel certification-status"><span className="cert-large-icon"><ShieldCheck /></span><span className="eyebrow">Current status</span><h2>Your certification is <span>{profile.certificationStatus?.replaceAll("_", " ") || "not submitted"}</span></h2><StatusBadge value={profile.certificationStatus || "not_submitted"} /><p>{statusCopy(profile.certificationStatus)}</p>{profile.certificationUrl && <a className="button button--ghost" href={assetUrl(profile.certificationUrl)} target="_blank" rel="noreferrer"><FileCheck2 size={18} /> View submitted file</a>}</section><section className="panel upload-panel"><div className="panel-heading"><div><span className="eyebrow">Submit documents</span><h2>Upload certification</h2></div><BadgeCheck /></div><p>Upload your current organic or farm certification document. Submitting a new file changes the status to pending review.</p><button className="cert-dropzone" type="button" onClick={() => inputRef.current?.click()}><UploadCloud /><strong>{file ? file.name : "Choose certification file"}</strong><span>PDF, PNG, or JPG · Maximum 8 MB</span><input ref={inputRef} type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={(e) => setFile(e.target.files[0])} /></button><button className="button button--full" disabled={!file || uploading} onClick={upload}>{uploading ? "Uploading…" : "Submit for review"}</button><div className="cert-guidance"><h3>Before you submit</h3><ul><li>Make sure the farm or business name is visible.</li><li>Use a clear, readable, current document.</li><li>Organic products require verified certification.</li></ul></div></section></div></div>;
}

function statusCopy(status) { if (status === "verified") return "Your farm has been verified. Organic listings can be approved when they meet marketplace requirements."; if (status === "pending") return "Your document is waiting for an administrator to review it."; if (status === "rejected") return "The last submission was not approved. Review your document and submit an updated file."; return "No certification has been submitted yet. You can still list non-organic products."; }
