import { Link } from "react-router-dom";
import { ArrowRight, Leaf, Minus, Plus, ShoppingBasket, Trash2, Truck } from "lucide-react";
import { EmptyState, PageHeader } from "../../components/UI";
import { useCart } from "../../context/CartContext";
import { money } from "../../utils/format";

export default function CartPage() {
  const { items, subtotal, deliveryFee, total, supplierCount, setQuantity, removeItem } = useCart();
  return <div><PageHeader eyebrow="Your basket" title="Review your cart" description={items.length ? `${items.length} products from ${supplierCount} local ${supplierCount === 1 ? "supplier" : "suppliers"}.` : "Your next local harvest starts here."} />{!items.length ? <EmptyState icon={ShoppingBasket} title="Your cart is empty" description="Browse the marketplace and add fresh local products." action={<Link className="button" to="/marketplace">Explore the marketplace</Link>} /> : <div className="cart-layout"><section className="panel cart-list">{items.map(({ product, quantity }) => <article className="cart-item" key={product._id}><div className={`cart-product-image produce-art produce-art--${product.category}`}><Leaf /></div><div className="cart-product-info"><span>{product.category} · {product.organic ? "Organic" : "Local"}</span><h3>{product.name}</h3><p>{product.supplier?.businessName || product.supplier?.name || "Local supplier"}</p><button type="button" onClick={() => removeItem(product._id)}><Trash2 size={15} /> Remove</button></div><div className="quantity-control"><button type="button" onClick={() => setQuantity(product._id, quantity - 1)}><Minus size={15} /></button><input type="number" min={product.minOrderQty || 1} max={product.stock} value={quantity} onChange={(e) => setQuantity(product._id, e.target.value)} aria-label={`Quantity for ${product.name}`} /><button type="button" onClick={() => setQuantity(product._id, quantity + 1)}><Plus size={15} /></button><small>{product.unit}</small></div><div className="cart-price"><strong>{money(product.price * quantity)}</strong><span>{money(product.price)} / {product.unit}</span></div></article>)}</section><aside className="panel order-summary"><span className="eyebrow">Order summary</span><h2>Your total</h2><div className="summary-lines"><span>Produce subtotal <b>{money(subtotal)}</b></span><span>Estimated delivery <b>{deliveryFee ? money(deliveryFee) : "Free"}</b></span></div><div className="summary-total"><span>Estimated total</span><strong>{money(total)}</strong></div><p className="summary-note"><Truck size={17} /> Orders are separated by supplier. Delivery is free for each supplier subtotal above ₹1,000.</p><Link className="button button--full button--large" to="/checkout">Continue to checkout <ArrowRight size={18} /></Link><Link className="continue-link" to="/marketplace">Continue shopping</Link></aside></div>}</div>;
}
