import { useEffect, useState } from "react";
import { Scale, ShieldCheck, TriangleAlert } from "lucide-react";
import api, { apiError } from "../../api/client";
import { EmptyState, ErrorState, Field, Loader, Modal, PageHeader, StatusBadge } from "../../components/UI";
import { useAuth } from "../../context/AuthContext";
import { useToast } from "../../context/ToastContext";
import { dateTime, shortId, title } from "../../utils/format";

export default function DisputesPage() {
  const { user } = useAuth(); const { showToast } = useToast();
  const [disputes, setDisputes] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState(null); const [resolution, setResolution] = useState({ status: "resolved", resolution: "" }); const [working, setWorking] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { setDisputes((await api.get("/disputes")).data); } catch (err) { setError(apiError(err)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const resolve = async () => { setWorking(true); try { await api.patch(`/disputes/${selected._id}/resolve`, resolution); setSelected(null); showToast("Dispute outcome recorded."); load(); } catch (err) { showToast(apiError(err), "error"); } finally { setWorking(false); } };
  return <div><PageHeader eyebrow="Resolution centre" title="Disputes" description={user.role === "admin" ? "Review marketplace issues and create clear, documented outcomes." : "Track issues connected to your orders and their resolution."} />{loading ? <Loader label="Loading disputes…" /> : error ? <ErrorState message={error} retry={load} /> : disputes.length ? <div className="dispute-list">{disputes.map((dispute) => <article className="panel dispute-card" key={dispute._id}><div className="dispute-top"><span className="dispute-icon"><TriangleAlert /></span><div><span className="eyebrow">Order {shortId(dispute.order?._id || dispute.order)}</span><h3>{dispute.reason}</h3><p>Opened {dateTime(dispute.createdAt)} by {dispute.openedBy?.businessName || dispute.openedBy?.name}</p></div><StatusBadge value={dispute.status} /></div>{dispute.description && <p className="dispute-description">{dispute.description}</p>}<div className="dispute-parties"><span><small>Opened by</small><strong>{dispute.openedBy?.name}</strong></span><span><small>Against</small><strong>{dispute.against?.name}</strong></span>{dispute.resolution && <span><small>Resolution</small><strong>{dispute.resolution}</strong></span>}</div>{user.role === "admin" && !["resolved", "rejected"].includes(dispute.status) && <button className="button button--small" onClick={() => { setSelected(dispute); setResolution({ status: "resolved", resolution: "" }); }}><Scale size={17} /> Resolve dispute</button>}</article>)}</div> : <EmptyState icon={ShieldCheck} title="No disputes" description={user.role === "admin" ? "The marketplace currently has no reported issues." : "You can open a dispute from an order detail page if something goes wrong."} />}{user.role === "admin" && <Modal open={Boolean(selected)} onClose={() => setSelected(null)} title="Resolve dispute" footer={<><button className="button button--ghost" onClick={() => setSelected(null)}>Cancel</button><button className="button" disabled={!resolution.resolution || working} onClick={resolve}>{working ? "Saving…" : "Save outcome"}</button></>}><div className="form-stack"><p><strong>{selected?.reason}</strong></p><Field label="Outcome"><select value={resolution.status} onChange={(e) => setResolution({ ...resolution, status: e.target.value })}><option value="resolved">Resolved</option><option value="rejected">Rejected</option><option value="under_review">Keep under review</option></select></Field><Field label="Resolution notes" required><textarea rows="5" value={resolution.resolution} onChange={(e) => setResolution({ ...resolution, resolution: e.target.value })} placeholder="Explain the decision and any next steps…" /></Field></div></Modal>}</div>;
}
