import { useEffect, useState } from "react";
import { BadgeCheck, Boxes, Download, Leaf, ShieldCheck, UserCheck, UserRoundCheck, XCircle } from "lucide-react";
import api, { apiError, assetUrl } from "../../api/client";
import { EmptyState, ErrorState, Loader, PageHeader, StatusBadge } from "../../components/UI";
import { useToast } from "../../context/ToastContext";
import { date, money, title } from "../../utils/format";

export function SupplierReviewsPage() {
  const [suppliers, setSuppliers] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [working, setWorking] = useState(""); const { showToast } = useToast();
  const load = async () => { setLoading(true); setError(""); try { setSuppliers((await api.get("/admin/farmers/pending")).data); } catch (err) { setError(apiError(err)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const review = async (id, status) => { setWorking(id); try { await api.patch(`/admin/farmers/${id}/verify`, { status }); showToast(`Supplier certification ${status}.`); setSuppliers((items) => items.filter((item) => item._id !== id)); } catch (err) { showToast(apiError(err), "error"); } finally { setWorking(""); } };
  return <div><PageHeader eyebrow="Supplier trust" title="Certification reviews" description="Review pending farm documents and decide whether a supplier can be verified." />{loading ? <Loader label="Loading supplier review queue…" /> : error ? <ErrorState message={error} retry={load} /> : suppliers.length ? <div className="review-list">{suppliers.map((supplier) => <article className="panel review-card" key={supplier._id}><div className="review-person"><span className="review-avatar"><UserRoundCheck /></span><div><span className="eyebrow">Submitted {date(supplier.updatedAt)}</span><h2>{supplier.supplierProfile?.farmName || supplier.businessName || supplier.name}</h2><p>{supplier.name} · {supplier.email}</p></div><StatusBadge value={supplier.supplierProfile?.certificationStatus} /></div><div className="review-details"><span><small>Location</small><strong>{supplier.address?.city || "Not provided"}{supplier.address?.state && `, ${supplier.address.state}`}</strong></span><span><small>Delivery radius</small><strong>{supplier.supplierProfile?.deliveryRadiusKm || 25} km</strong></span><span><small>Practices listed</small><strong>{supplier.supplierProfile?.sustainabilityPractices?.length || 0}</strong></span></div>{supplier.supplierProfile?.description && <p className="review-description">{supplier.supplierProfile.description}</p>}<div className="review-actions">{supplier.supplierProfile?.certificationUrl && <a className="button button--ghost" target="_blank" rel="noreferrer" href={assetUrl(supplier.supplierProfile.certificationUrl)}><Download size={17} /> View document</a>}<button className="button button--danger-ghost" disabled={working === supplier._id} onClick={() => review(supplier._id, "rejected")}><XCircle size={17} /> Reject</button><button className="button" disabled={working === supplier._id} onClick={() => review(supplier._id, "verified")}><BadgeCheck size={17} /> Verify supplier</button></div></article>)}</div> : <EmptyState icon={UserCheck} title="Supplier queue is clear" description="New certification submissions will appear here for review." />}</div>;
}

export function ProductReviewsPage() {
  const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [working, setWorking] = useState(""); const { showToast } = useToast();
  const load = async () => { setLoading(true); setError(""); try { setProducts((await api.get("/admin/products/pending")).data); } catch (err) { setError(apiError(err)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const review = async (id, status) => { setWorking(id); try { await api.patch(`/admin/products/${id}/approve`, { status }); showToast(`Product ${status}.`); setProducts((items) => items.filter((item) => item._id !== id)); } catch (err) { showToast(apiError(err), "error"); } finally { setWorking(""); } };
  return <div><PageHeader eyebrow="Marketplace quality" title="Product reviews" description="Check pending listings before making them visible to buyers." />{loading ? <Loader label="Loading product review queue…" /> : error ? <ErrorState message={error} retry={load} /> : products.length ? <div className="product-review-grid">{products.map((product) => { const supplier = product.supplier || {}; const verified = supplier.supplierProfile?.certificationStatus === "verified"; return <article className="panel product-review-card" key={product._id}><div className={`review-product-art produce-art produce-art--${product.category}`}><Leaf /><StatusBadge value={product.approvalStatus} /></div><div className="product-review-body"><span className="eyebrow">{title(product.category)}</span><h2>{product.name}</h2><p>{product.description || "No product description provided."}</p><div className="review-details"><span><small>Price</small><strong>{money(product.price)} / {product.unit}</strong></span><span><small>Stock</small><strong>{product.stock} {product.unit}</strong></span><span><small>Minimum</small><strong>{product.minOrderQty} {product.unit}</strong></span></div><div className={`supplier-check ${verified ? "verified" : ""}`}><ShieldCheck /><div><small>Supplier</small><strong>{supplier.businessName || supplier.name}</strong><span>Certification: {title(supplier.supplierProfile?.certificationStatus || "not submitted")}</span></div></div>{product.organic && !verified && <div className="form-alert">Organic products cannot be approved until the supplier certification is verified.</div>}<div className="review-actions"><button className="button button--danger-ghost" disabled={working === product._id} onClick={() => review(product._id, "rejected")}><XCircle size={17} /> Reject</button><button className="button" disabled={working === product._id || (product.organic && !verified)} onClick={() => review(product._id, "approved")}><BadgeCheck size={17} /> Approve product</button></div></div></article>; })}</div> : <EmptyState icon={Boxes} title="Product queue is clear" description="New and materially updated listings will appear here." />}</div>;
}
